# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none

pool:
  vmImage: windows-latest

variables:
- group: excel-dna

resources:
  repositories:
  - repository: IntelliSense
    endpoint: arup-group
    type: github
    name: Excel-DNA/IntelliSense
    ref: e7871efe9bfbc2aaefc68bbd88ddb66d81c0fb9a    
  - repository: Registration
    endpoint: arup-group
    type: github
    name: Excel-DNA/Registration
    ref: 8b9dcd0656d788f22d2be7e846de13476b482c50   
  - repository: ExcelDnaDoc
    endpoint: arup-group
    type: github
    name: Excel-DNA/ExcelDnaDoc
    ref: d76f144af1ef4fa32341263cf26308d3d3886324    

steps:
  - checkout: self
  - checkout: IntelliSense
  - checkout: Registration
  - checkout: ExcelDnaDoc
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      workingFolder: ExcelDna\MasterBuild
      script: |
        $Env:PACKAGE_VERSION = "$(cat .\ExcelDna\version.txt)+$($Env:Build_BuildId%65536)"
        .\MasterBuild.cmd
  - task: DotNetCoreCLI@2
    inputs:
      command: push
      packagesToPush: '$(Build.SourcesDirectory)/ExcelDna/Package/nupkg/*.nupkg'
      nuGetFeedType: internal
      publishVstsFeed: 'a704a910-c375-48a7-9ea9-dd5b985bdf8c'