# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none

pool:
  vmImage: windows-latest

variables:
- group: excel-dna

resources:
  repositories:
  - repository: IntelliSense
    endpoint: arup-group
    type: github
    name: Excel-DNA/IntelliSense
    ref: c730c636feb63768c612b8a50988cb004eca8909
  - repository: Registration
    endpoint: arup-group
    type: github
    name: Excel-DNA/Registration
    ref: 79e6c3863f4e52e87fc71224081441160df1b7ba   
  - repository: ExcelDnaDoc
    endpoint: arup-group
    type: github
    name: Excel-DNA/ExcelDnaDoc
    ref: 4b0bf7057a0d0ab1f0128d708f1c8390db693dd5    

steps:
  - checkout: self
  - checkout: IntelliSense
  - checkout: Registration
  - checkout: ExcelDnaDoc
  - task: BatchScript@1
    inputs:
      filename: ExcelDna\MasterBuild\MasterBuild.cmd
      workingFolder: ExcelDna\MasterBuild
  - task: NuGetAuthenticate@1
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      packagesToPush: '$(Build.SourcesDirectory)/**/*.nupkg'
      publishVstsFeed: ArupCompute/arupcomputedevops_test
      allowPackageConflicts: true